#!/bin/bash
#
# steps - partition, split
# times - partition, split, total
# space - total pace
#!/bin/bash
# Three arguments: 1. 
#srt = qsort(type=0, partType = 0, size = size, ceiling = 2000000, asInt = isInt)
#if [ $# -eq 0 ]; then
#    echo "Usage: "
#    echo "./run <script_name>  <maximum_set_size> <script_type>"
#    echo "where script type is an integer"
#    exit 0
#fi

#SCRIPTNAME=$1
#parser.add_argument('-t', dest = 'type')
#parser.add_argument('-s', dest = 'inputSize')
#parser.add_argument('-pt', dest = 'partType')
#parser.add_argument('-c', dest = 'ceiling')
#parser.add_argument('-i', dest = 'asInt')
SCRIPTNAME='qsort.py'

bn=`basename $SCRIPTNAME .py`
#MAX=$2
MAX=100000000
res="_Results"
experiments=5
if [ ! -d "$bn$res" ]; then
    mkdir "$bn$res"
fi
t=0
tm=6
pt=0
ptm=7
i=1
j=0
n=0
pivot=1
asInt=1
while [ $pt -lt $ptm ]
do
    while [ $t -lt $tm ]
    do
        while [ $i -lt $MAX ]
        do
            while [ $j -lt $experiments ]
            do
               # echo "python3 $SCRIPTNAME -t $t -s $i -pt $pt -c 1000 -i 'True'"
                python3 $SCRIPTNAME -t $t -s $i -pt $pt -c 1000 -i 'True' -piv >>$bn$res/$n
                j=$(($j+1))
            done
            j=0
            i=$(($i*10))
            n=$(($n+1))
        done
        i=1
        t=$(($t+1))
    done
    t=0
    pt=$(($pt+1))
done
