#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: ./run <sorts_loc> <algortihms_file_loc>"
    exit 1
fi


PARENTDIR=`pwd`
RESULTSDIR="$PARENTDIR/results"
echo $RESULTSDIR
SORTLOC=$1
ALGORITHMS=$2
echo $SORTLOC
echo $ALGORITHMS


#Create results dir if not already exists
if [ ! -d "$RESULTSDIR" ]; then
    mkdir "$RESULTSDIR"
fi


#change directory to sort location
cd $SORTLOC


#===========================Variables=========================================

SCRIPTNAME=$(<$ALGORITHMS)
MAX=10001
ceiling=1000 #maximum value in the array
t=0 #sort type, in my case I have several sorts in one file
tm=2 #maximum amount of sorts, set to one if you have only one sort per file, it is safe to crank it up to 3 for quicksort
pt=0 #partition type, in total we have 7 of them defined in base.py
ptm=7 #partition types maximum
currSize=1 #starting size
currExperiment=0 #number of experiments
experiments=1
pivot=1 #will evaluate to true if 1 or to false if 0, needed for quicksorts
asInt=1 #will evaluate to true if 1 to false if 0
cutoff=10
cutoffMax=1000000

#=============================================================================
Color_OFF="[0m"
Bold="[1m"
c2m="[2m"
c3m="[3m"
Underline="[4m"
Blink="[5m"
c6m="[6m"
Reverse="[7m"
Color0="[30m"
Color1="[31m"
Color2="[32m"
Color3="[33m"
Color4="[34m"
Color5="[35m"
Color6="[36m"
Color7="[37m"
Color8="[90m"
Color9="[91m"
Color10="[92m"
Color11="[93m"
Color12="[94m"
Color13="[95m"
Color14="[96m"
Color15="[97m"

info() {
    echo ""
    echo "======================================================"
    echo $Color2
    echo "Next test: "
    echo $Color9
    echo "type            $t"
    echo "type max        $tm"
    echo "partition type  $pt"
    echo "partition max   $ptm"
    echo "currSize        $currSize"
    echo "currExperiment  $currExperiment"
    echo "pivot           $pivot"
    echo "asInt           $asInt"
    echo "cutoff          $cutoff"
    echo "cutoffMax       $cutoffMax"
    echo $Color15
    echo "Done"
    echo $Color_OFF
}

echo "Working ..."

for algorithm in $SCRIPTNAME #for all files:
do
    echo "$algorithm"
done

for algorithm in $SCRIPTNAME #for all files:
do
	f=`basename $algorithm .py`
    while [ $pt -lt $ptm ] #for all partition types
    do
        echo "partitions"
        while [ $t -lt $tm ] #for all sort types
        do
            echo "types"
            while [ $currSize -lt $MAX ] #for sizes from currSize to MAX
            do
                echo "sizes"
                while [ $currExperiment -lt $experiments ] #try number of times = experiments
                do
                    echo "experiments"
                    info
                    echo $Color5
                    echo "python3 $algorithm -t $t -s $currSize -pt $pt -c $ceiling -i $asInt -piv $pivot -cut $cutoff -f $f"
                    echo $Color_OFF
                    python3 $algorithm -t $t -s $currSize -pt $pt -c $ceiling -i $asInt -piv $pivot -cut $cutoff -f $f
                    currExperiment=$(($currExperiment+1))
                done
                currExperiment=0
                if [ $currSize -ge 1000000 ]; then
                    currSize=$(($currSize+1000000))
                else
                    currSize=$(($currSize*10))
                fi
            done
            currSize=1
            t=$(($t+1))
        done
        t=0
        pt=$(($pt+1))
    done
    pt=0
done

 mv *.json $RESULTSDIR
 echo "results for moved to $RESULTSDIR"
